### ISSUE TITLE
[EPIC:] Implement API-business logic

### ISSUE THREAD

**Issue by ByteOtter** [The-Nazara-Project/Nazara#60]
# What's this about?

This epic collects all it's sub-issues into one place.

This epic is about the implementation of Nazara's part of the business logic, which talks to the NetBox API.

### `Publisher`
- [ ] #56 - Implement Machine registration logic
- [ ] #57 - Implement logic to update an existing machine
- [ ] #58 - Implement VM registration logic
- [ ] #59 - Implement VM update logic

## Acceptance criteria

This epic is done once all of the above issues have been completed and these criteria are met:

- [ ] Able to create machines
- [ ] Able to update machines
- [ ] Able to create VMs
- [ ] Able to update VMs

**Comment by ByteOtter** [comment]
With machine registration and update being fundamentally complete, we now have the state of a MVP.

**Comment by ByteOtter** [comment]
With Beta 1 out the door, implementing VM creation and update is the next priority feature.

**Comment by ByteOtter** [comment]
Finally, this is done by #107.
Thanks to @marv7000 for his support.
