### ISSUE TITLE
[EPIC:] Refine application configuration

### ISSUE THREAD

**Issue by ByteOtter** [The-Nazara-Project/Nazara#62]
# What's this about?

This Epic will provide one place to link several issues.

This Epic is about refining and reworking Nazara's configuration component.

### `configuration` Module

- [ ] #26 - Add `--write-config` flag to write CLI parameters to config file
- [ ] #27 - Add `--no-config` flag to run simply via CLI parameters
- [ ] #29 - Avid `panic` on empty config file (change behaviour)
- [ ] #38 - Fix config file validation error when cli parameters are provided (Change to warning)

## Acceptance criteria

- [ ] `--write-config` Flag exists and works as intended
- [ ] `--no-config` Flag exists and works as intended
- [x] `panic` behaviour changed in #29 
- [ ] Validation error changed into validation warning when config parameters provided via cli

**Comment by ByteOtter** [comment]
This epic has been obsoleted by:

Issue #116 
Epic: #112
