### ISSUE TITLE
[EPIC] Port API calls to NetBox `v4.x`

### ISSUE THREAD

**Issue by ByteOtter** [The-Nazara-Project/Nazara#74]
### Nazara Version

n/A

### Feature Type

New Core Feature

### Affected Module

API Connection

## What?

To ease production of a minimal viable product, we will initially pin the implementation of Nazara to NetBox `v3.6.9` as implementing core funcitonality alongside ever changing API structure is simply not feasable.

After #73 we will investigate porting these changes to the latest `v4.x`.

This will require rewriting the `publisher`, `translator` and probably parts of the `configuration` modules.

## Prerequisites

- [x] Fix #73 
- [ ] Fix #87 
- [ ] Fix #58 (optional)

## Steps

- [ ] Backup current `main` branch to `v0.1.0-alpha.3` branch to keep compatibility with NetBox `v3.6.9`
- [x] Create newest `thanix_client` crate
- [x] Import newest crate into NetBox
- [x] Fix compilation errors
    - [x] Rewrite payload generation in `translator.rs`
    - [x] Add potentially new required information fields to `configuration_parser.rs` if necessary
    - [x] If necessary, change flow of request handling in `publisher.rs`
    - [x] If necessary, change api request sending in `api_client.rs` (most likely not needed)
- [x] Create/Change/Update unittests accordingly
- [x] Update documentation to list the latest version supported by this current implementation
- [x] Update documentation, docstrings etc. to the new configuration parameters (if any) and adjust function/struct docstrings as they evolve
- [x] Update Version number in `Cargo.toml`

## Steps post-merge

- [ ] Tag Nazara as `v0.1.0-rc1` in accordance with semantic versioning

**Comment by ByteOtter** [comment]
@SchoolGuy assigning you too, as you are the one responsible for your NetBox instance.
